# This file was generated by GoReleaser. DO NOT EDIT.
cask "ec2rdp" do
  name "ec2rdp"
  desc "Remote Desktop Utility for Amazon EC2."
  homepage "https://github.com/stknohg/ec2rdp"
  version "0.8.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ec2rdp"

  on_macos do
    on_intel do
      url "https://github.com/stknohg/ec2rdp/releases/download/v#{version}/ec2rdp-darwin-x64.tar.gz"
      sha256 "d924ff33aace1bffa895096a840816806b1306a821e06367c00c507798eff89d"
    end
    on_arm do
      url "https://github.com/stknohg/ec2rdp/releases/download/v#{version}/ec2rdp-darwin-arm64.tar.gz"
      sha256 "1702decc842230191e0ea5cc6fa3239a17223b32b145dde0081eb1ba5e57a266"
    end
  end

  # No zap stanza required
end
