# This file was generated by GoReleaser. DO NOT EDIT.
cask "ec2rdp" do
  desc "Remote Desktop Utility for Amazon EC2."
  homepage "https://github.com/stknohg/ec2rdp"
  version "0.8.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ec2rdp"

  on_macos do
    on_intel do
      url "https://github.com/stknohg/ec2rdp/releases/download/v0.8.4/ec2rdp-darwin-x64.tar.gz"
      sha256 "8871760b6510d9254452c0445a05776b665564cb9b1a7d1ca42198055455751a"
    end
    on_arm do
      url "https://github.com/stknohg/ec2rdp/releases/download/v0.8.4/ec2rdp-darwin-arm64.tar.gz"
      sha256 "c09abf9b2af865bfe18b401e41f7ff3174056d812e6775355b847b443d48301c"
    end
  end

  # No zap stanza required
end
