# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2rdp < Formula
  desc "Remote Desktop Utility for Amazon EC2."
  homepage "https://github.com/stknohg/ec2rdp"
  version "0.5.0"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stknohg/ec2rdp/releases/download/v0.5.0/ec2rdp-darwin-x64.tar.gz"
      sha256 "2a1bbe75c93fb594812f728a46d21819ef2c66099cd4a4848761ca846388ea09"

      def install
        bin.install "ec2rdp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stknohg/ec2rdp/releases/download/v0.5.0/ec2rdp-darwin-arm64.tar.gz"
      sha256 "300743e231b4e9ed22741cfe8e3550e10b81316c38a33e4e9a9a955f21883cce"

      def install
        bin.install "ec2rdp"
      end
    end
  end
end
