# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2rdp < Formula
  desc "Remote Desktop Utility for Amazon EC2."
  homepage "https://github.com/stknohg/ec2rdp"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stknohg/ec2rdp/releases/download/v0.2.0/ec2rdp-darwin-arm64.tar.gz"
      sha256 "682705457613e6516ca3ca8c4ab2fe638deca080339a841921ba7307edf5f976"

      def install
        bin.install "ec2rdp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stknohg/ec2rdp/releases/download/v0.2.0/ec2rdp-darwin-x64.tar.gz"
      sha256 "78d5bb1e656bdc3d73d533512ea5b0f1803684a231df04afff60e9c5d9048db6"

      def install
        bin.install "ec2rdp"
      end
    end
  end
end
